openapi: 3.0.3
info:
  title: Neenaryex API
  description: Fastify API for Neenaryex
  version: 0.1.0
components:
  schemas:
    AuthRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
paths:
  /auth:
    post:
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthRequest"
      responses:
        "201":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    anyOf:
                      - type: string
                        enum:
                          - Ok
                      - type: string
                        enum:
                          - Ko
                  message:
                    type: string
                  error: {}
                required:
                  - result
  /user/me:
    get:
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - type: object
                    properties:
                      result:
                        anyOf:
                          - type: string
                            enum:
                              - Ok
                          - type: string
                            enum:
                              - Ko
                      message:
                        type: string
                      error: {}
                    required:
                      - result
                  - type: object
                    properties:
                      payload:
                        type: object
                        allOf:
                          - type: object
                            properties:
                              id:
                                type: string
                            required:
                              - id
                          - type: object
                            properties:
                              username:
                                type: string
                              timestamp:
                                type: number
                              ip:
                                type: string
                            required:
                              - username
                              - timestamp
                              - ip
        default:
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    anyOf:
                      - type: string
                        enum:
                          - Ok
                      - type: string
                        enum:
                          - Ko
                  message:
                    type: string
                  error: {}
                required:
                  - result
  /user/logout:
    get:
      responses:
        default:
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    anyOf:
                      - type: string
                        enum:
                          - Ok
                      - type: string
                        enum:
                          - Ko
                  message:
                    type: string
                  error: {}
                required:
                  - result
  /user/sync/download:
    get:
      responses:
        default:
          description: Default Response
          content:
            application/json:
              schema:
                anyOf:
                  - type: string
                    enum:
                      - Ok
                  - type: string
                    enum:
                      - Ko
tags:
  - name: Auth
    description: Auth related endpoint
